CREATE TABLE `icecast`.`access_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(255) NULL,
  `filename` VARCHAR(255) NULL,
  `is_download` TINYINT NULL,
  `session_time` INT(11) NULL,
  `is_redirect` TINYINT NULL,
  `event_category` VARCHAR(255) NULL,
  `event_action` VARCHAR(255) NULL,
  `lineno` INT(11) NULL,
  `status` VARCHAR(255) NULL,
  `is_error` TINYINT NULL,
  `event_name` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  `path` VARCHAR(255) NULL,
  `extension` VARCHAR(255) NULL,
  `referrer` VARCHAR(255) NULL,
  `userid` VARCHAR(255) NULL,
  `length` INT(18) NULL,
  `user_agent` VARCHAR(512) NULL,
  `generation_time_milli` INT(18) NULL,
  `query_string` VARCHAR(255) NULL,
  `is_robot` TINYINT NULL,
  `full_path` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_access` (`date`,`lineno`));
